Docker for LBNE

* This Package

This package builds Docker containers and through them builds LBNE
software.  Some more details are at:

https://lbne.bnl.gov/wiki/Building_in_Docker

* Installation

** Docker

See Docker's own installation instructions for your platform for details.  

This package assumes the native host user has correct permissions.

** Python Modules

This package drives Docker via python.  For now, you must install things manually.

#+BEGIN_EXAMPLE
  $ virtualenv venv
  $ source venv/bin/activate
  $ pip install docker-py=0.5.3
  $ pip install docker-map
  $ pip install click
#+END_EXAMPLE

Note, it's important for now to explicitly install =docker-py= version 0.5.3, at least when running on an Ubuntu 14.04 host. 

* Configuration

See [[./lbne-docker.cfg]].  The LBNE wiki link has some background info.

* Use

#+BEGIN_EXAMPLE
  $ python lbne-docker.py lbne-0.5.1-fedora-20-1
#+END_EXAMPLE

* Environment

The "environment" (using the language from the LBNE wiki page) is handled by hacking on [[./dot.profile]].  

** Life behind a firewall

If you live behind a firewall you may need to explicitly set the DNS for Docker to use and maybe also set HTTP or FTP proxy variables.  For Docker itself add  =--dns=  and =export= entries to =/etc/default/docker.io= and restart the daemon.  You may further need to edit the [[./dot.profile]] file to set any environment variables.   Do so by keying off the DNS settings.
