#!/bin/bash 

if [ -z "$1" ] ; then
    echo "usage: reups <package> ..."
    exit 1
fi

for package in $* 
do
    rm tmp/upsproducts/$package/v*/*/ups/${package}.table
    rm tmp/controls/${package}_ups*
done

./outland/wafit externals 

for package in $* 
do
    set -x
    tar -C products -xf tmp/upspack/${package}-*.tar.bz2
    set +x
done
