#!/bin/bash

# do some checks to make sure I didn't forget to do something

cd $HOME/lbne-build

if [ -z "$(git status | grep 'nothing to commit')" ] ; then
    echo "Dirty lbne-build/"
    exit 1
fi

if [ -n "$(git status | grep ahead)" ] ; then
    echo "Need to push lbne-build/"
    exit 1
fi
